services:
  prescriberpoint.journal.webapi:
    image: prescriberpoint.journal.webapi
    build:
      context: .
      dockerfile: src/PrescriberPoint.Journal.WebApi/Dockerfile
    environment:
      - ConnectionStrings__JournalDb=server=postgres;database=journaldb;uid=postgres;password=qwerty
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8081:8081"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: journaldb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"